# deploy/k8s/kafka-producer.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: producer
          image: gcr.io/my-project-for-bigquery-445809/ecommerce-producer:latest # 使用專案的 GCR / Artifact Registry
          command: ["python", "scripts/run_kafka_producer.py", "--delay", "1.0"]
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "ecommerce-kafka-kafka-bootstrap:9092" # 連線到 K8s 內部由 Strimzi 產生的 Kafka Bootstrap 服務
