# deploy/k8s/spark-consumer.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-consumer-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-consumer
  template:
    metadata:
      labels:
        app: spark-consumer
    spec:
      containers:
        - name: spark-consumer
          image: gcr.io/my-project-for-bigquery-445809/ecommerce-spark:latest # 包含 PySpark 與 BigQuery Connector 的 Docker Image
          command: ["python", "scripts/spark_bigquery_consumer.py"]
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "ecommerce-kafka-kafka-bootstrap:9092"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/secrets/google/gcp_key.json"
            - name: PROJECT_ID
              value: "my-project-for-bigquery-445809"
            - name: DATASET_ID
              value: "raw_ecommerce"
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
              readOnly: true
      volumes:
        - name: google-cloud-key
          secret:
            secretName: gcp-key-secret # 由 K8s Secret 機制載入的安全金鑰 (Production 環境建議改用 GKE Workload Identity 以免金鑰外洩)
