name: ecommerce_dbt

profile: ecommerce_dbt

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce_dbt:
    staging:
      +contract:
        enforced: true
      +materialized: view
      +schema: staging
    
    intermediate:
      +materialized: view
      +schema: intermediate

    marts:
      +materialized: table
      +schema: marts
